#!/usr/bin/env python3
"""
Jetson Orin NX deployment pipeline for Newgenes.

Prepares the fine-tuned model for TensorRT-LLM on Jetson Orin NX 16GB.

Strategy: Convert MLX LoRA adapter weights to HuggingFace PEFT format,
then use TensorRT-LLM with runtime LoRA on Jetson. This avoids the
quality loss from dequantize-merge-requantize.

Usage:
  python deploy_jetson.py prepare    # Convert adapter to PEFT format (run on Mac)
  python deploy_jetson.py package    # Create transfer package for Jetson

On Jetson:
  See jetson_setup.sh generated by 'package' command.
"""
import json, sys, os, shutil
from pathlib import Path

ADAPTER_PATH = Path("./adapters/gemma4-newgenes")
DEPLOY_DIR = Path("./jetson_deploy")
BASE_MODEL_HF = "google/gemma-4-26b-a4b-it"
BASE_MODEL_MLX = "mlx-community/gemma-4-26b-a4b-it-4bit"


def prepare():
    """Convert MLX LoRA adapter to HuggingFace PEFT format."""
    import numpy as np

    print("Converting MLX LoRA adapter to PEFT format...")

    DEPLOY_DIR.mkdir(exist_ok=True)
    peft_dir = DEPLOY_DIR / "peft_adapter"
    peft_dir.mkdir(exist_ok=True)

    # Load MLX adapter config
    with open(ADAPTER_PATH / "adapter_config.json") as f:
        mlx_config = json.load(f)

    # Load MLX adapter weights
    try:
        import mlx.core as mx
        from mlx.utils import tree_unflatten
        weights = dict(mx.load(str(ADAPTER_PATH / "adapters.safetensors")))
        print(f"  Loaded {len(weights)} weight tensors")
    except ImportError:
        print("  MLX not available, using safetensors directly")
        from safetensors import safe_open
        weights = {}
        with safe_open(str(ADAPTER_PATH / "adapters.safetensors"), framework="numpy") as f:
            for k in f.keys():
                weights[k] = f.get_tensor(k)

    # Map MLX weight names to PEFT names
    # MLX: language_model.model.layers.{i}.{module}.linear.lora_a
    # PEFT: base_model.model.language_model.model.layers.{i}.{module}.lora_A.weight
    peft_weights = {}
    for name, tensor in weights.items():
        if isinstance(tensor, np.ndarray):
            arr = tensor
        else:
            arr = np.array(tensor.astype(mx.float32))

        peft_name = "base_model.model." + name
        if '.lora_a' in peft_name:
            peft_name = peft_name.replace('.lora_a', '.lora_A.weight')
            arr = arr.T if arr.ndim == 2 else arr
        elif '.lora_b' in peft_name:
            peft_name = peft_name.replace('.lora_b', '.lora_B.weight')
            arr = arr.T if arr.ndim == 2 else arr

        # Remove .linear from path (PEFT doesn't use it)
        peft_name = peft_name.replace('.linear.', '.')

        peft_weights[peft_name] = arr
        print(f"  {name} -> {peft_name}  {arr.shape}")

    # Save PEFT weights
    try:
        from safetensors.numpy import save_file
        save_file(peft_weights, str(peft_dir / "adapter_model.safetensors"))
    except ImportError:
        import torch
        from safetensors.torch import save_file as save_torch
        torch_weights = {k: torch.from_numpy(v) for k, v in peft_weights.items()}
        save_torch(torch_weights, str(peft_dir / "adapter_model.safetensors"))

    # Collect target module names from weight keys
    target_modules = set()
    for name in weights.keys():
        parts = name.split('.')
        for j, p in enumerate(parts):
            if p in ('self_attn', 'mlp', 'experts', 'router'):
                module_path = '.'.join(parts[j:])
                module_path = module_path.split('.lora_')[0]
                module_path = module_path.replace('.linear', '')
                target_modules.add(module_path)
                break

    # Write PEFT adapter_config.json
    peft_config = {
        "auto_mapping": None,
        "base_model_name_or_path": BASE_MODEL_HF,
        "bias": "none",
        "fan_in_fan_out": False,
        "inference_mode": True,
        "init_lora_weights": True,
        "layers_to_transform": None,
        "layers_pattern": None,
        "lora_alpha": mlx_config["lora_parameters"]["alpha"],
        "lora_dropout": mlx_config["lora_parameters"]["dropout"],
        "modules_to_save": None,
        "peft_type": "LORA",
        "r": mlx_config["lora_parameters"]["rank"],
        "revision": None,
        "target_modules": sorted(target_modules),
        "task_type": "CAUSAL_LM",
    }
    with open(peft_dir / "adapter_config.json", "w") as f:
        json.dump(peft_config, f, indent=2)

    print(f"\n  PEFT adapter saved to {peft_dir}/")
    print(f"  Weights: {os.path.getsize(peft_dir / 'adapter_model.safetensors') / 1e6:.1f} MB")


def package():
    """Create a transfer package with everything needed for Jetson deployment."""
    print("Creating Jetson deployment package...")

    DEPLOY_DIR.mkdir(exist_ok=True)
    peft_dir = DEPLOY_DIR / "peft_adapter"

    if not peft_dir.exists():
        print("  Run 'prepare' first to convert adapter weights")
        return

    # Copy MLX adapter as backup
    mlx_dir = DEPLOY_DIR / "mlx_adapter"
    if not mlx_dir.exists():
        shutil.copytree(ADAPTER_PATH, mlx_dir)

    # Write system prompt
    system_msg = (
        "You are a synthetic biology assistant that converts natural language "
        "descriptions of genetic circuits into structured JSON. Return a single "
        "JSON object with these fields:\n\n"
        "- \"name\": short circuit name\n"
        "- \"components\": array of {\"name\", \"type\", \"description\"} — each part in the circuit\n"
        "- \"interactions\": array of {\"from\", \"to\", \"type\"} — wiring between parts\n"
        "- \"behavior\": what the circuit does\n"
        "- \"organism\": host organism\n\n"
        "Component types: promoter, rbs, cds, terminator, operator, other.\n"
        "Interaction types: transcription (promoter->cds), translation (rbs->cds), "
        "activation (cds->promoter/operator), repression (cds->promoter/operator).\n\n"
        "Rules:\n"
        "- Every gene needs: promoter, rbs, cds, terminator\n"
        "- Use snake_case names\n"
        "- Every from/to must reference an existing component name\n"
        "- Respond with valid JSON only, no explanation"
    )
    with open(DEPLOY_DIR / "system_prompt.txt", "w") as f:
        f.write(system_msg)

    # Write Jetson setup script
    setup_script = r"""#!/bin/bash
# Newgenes — Jetson Orin NX 16GB deployment with TensorRT-LLM
# Run this script on the Jetson after transferring the jetson_deploy/ folder.

set -e

echo "=== Newgenes Jetson Deployment ==="

# --- Step 1: Install dependencies ---
echo "[1/5] Installing dependencies..."
pip3 install --upgrade pip
pip3 install torch --index-url https://developer.download.nvidia.com/compute/redist/jp/v61
pip3 install tensorrt-llm --extra-index-url https://pypi.nvidia.com
pip3 install transformers peft safetensors huggingface_hub

# --- Step 2: Download base model (INT4 AWQ quantized for 16GB) ---
echo "[2/5] Downloading quantized base model..."
# Use the INT4 AWQ version — fits in 16GB with room for KV cache
python3 -c "
from huggingface_hub import snapshot_download
snapshot_download(
    'google/gemma-4-26b-a4b-it',
    local_dir='./base_model',
    ignore_patterns=['*.bin', '*.h5'],
)
"

# --- Step 3: Quantize with TRT-LLM ---
echo "[3/5] Quantizing model for TensorRT-LLM..."
python3 -c "
from tensorrt_llm import quantization as quant
from tensorrt_llm.models import GemmaForCausalLM

# INT4 AWQ quantization — best for Orin NX tensor cores
model = GemmaForCausalLM.from_hugging_face(
    './base_model',
    dtype='float16',
    quant_config=quant.QuantConfig(
        quant_algo=quant.QuantAlgo.W4A16_AWQ,
        group_size=128,
    ),
)
model.save('./trt_checkpoint')
"

# --- Step 4: Build TRT-LLM engine ---
echo "[4/5] Building TensorRT-LLM engine..."
trtllm-build \
    --checkpoint_dir ./trt_checkpoint \
    --output_dir ./trt_engine \
    --gemm_plugin float16 \
    --max_batch_size 1 \
    --max_input_len 2048 \
    --max_seq_len 4096 \
    --lora_plugin float16 \
    --lora_dir ./peft_adapter \
    --max_lora_rank 8

# --- Step 5: Test ---
echo "[5/5] Testing..."
python3 test_inference.py

echo "=== Deployment complete ==="
"""
    with open(DEPLOY_DIR / "jetson_setup.sh", "w") as f:
        f.write(setup_script)
    os.chmod(DEPLOY_DIR / "jetson_setup.sh", 0o755)

    # Write test inference script
    test_script = r"""#!/usr/bin/env python3
\"\"\"Test inference on Jetson with TensorRT-LLM.\"\"\"
import json, time

def test_trtllm():
    from tensorrt_llm.runtime import ModelRunner

    runner = ModelRunner.from_dir(
        "./trt_engine",
        lora_dir="./peft_adapter",
    )

    with open("system_prompt.txt") as f:
        system_msg = f.read()

    test_prompts = [
        "Express GFP from a constitutive promoter in E. coli",
        "Build a NOT gate: constitutive TetR represses GFP, so adding aTc turns GFP ON",
        "Create a toggle switch using LacI and TetR that can flip between two stable states",
        "Design an arsenic biosensor where ArsR detects arsenite and derepresses GFP",
        "Engineer a violacein pathway with VioA through VioE from a T7 promoter",
    ]

    print(f"\nTesting {len(test_prompts)} prompts...\n")
    for i, prompt in enumerate(test_prompts):
        t0 = time.time()
        output = runner.generate(
            [f"<start_of_turn>system\n{system_msg}<end_of_turn>\n"
             f"<start_of_turn>user\n{prompt}<end_of_turn>\n"
             f"<start_of_turn>model\n"],
            max_new_tokens=2048,
            temperature=0.1,
            top_p=0.95,
        )
        elapsed = time.time() - t0
        text = output[0].text
        try:
            r = json.loads(text)
            nc = len(r.get("components", []))
            ni = len(r.get("interactions", []))
            print(f"[{i+1}] OK  {elapsed:.1f}s  {nc} components, {ni} interactions")
        except json.JSONDecodeError:
            print(f"[{i+1}] FAIL  {elapsed:.1f}s  (invalid JSON)")
            print(f"     {text[:200]}")

    print("\nDone.")


def test_peft_fallback():
    \"\"\"Fallback: test with HuggingFace PEFT if TRT-LLM isn't available.\"\"\"
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    print("Loading base model...")
    tokenizer = AutoTokenizer.from_pretrained("./base_model")
    model = AutoModelForCausalLM.from_pretrained(
        "./base_model",
        torch_dtype=torch.float16,
        device_map="auto",
        load_in_4bit=True,
    )
    model = PeftModel.from_pretrained(model, "./peft_adapter")
    model.eval()

    with open("system_prompt.txt") as f:
        system_msg = f.read()

    prompt = "Express GFP from a constitutive promoter in E. coli"
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": prompt},
    ]
    inputs = tokenizer.apply_chat_template(messages, return_tensors="pt").to(model.device)

    t0 = time.time()
    with torch.no_grad():
        outputs = model.generate(inputs, max_new_tokens=512, temperature=0.1, top_p=0.95)
    elapsed = time.time() - t0

    text = tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)
    print(f"Response ({elapsed:.1f}s):")
    print(text[:500])


if __name__ == "__main__":
    try:
        test_trtllm()
    except ImportError:
        print("TensorRT-LLM not found, falling back to PEFT...")
        test_peft_fallback()
"""
    with open(DEPLOY_DIR / "test_inference.py", "w") as f:
        f.write(test_script)

    # Write deployment README
    readme = f"""# Newgenes — Jetson Orin NX Deployment

## Model
- Base: google/gemma-4-26b-a4b-it (26B MoE, ~4B active params)
- Fine-tuned: QLoRA rank 8, 1000 iterations on 1162 genetic circuit examples
- Eval score: 97.0/100 across 20 prompts (easy to expert)

## Contents
- peft_adapter/     — LoRA adapter in HuggingFace PEFT format
- mlx_adapter/      — Original MLX adapter (backup)
- system_prompt.txt — System prompt for inference
- jetson_setup.sh   — Automated setup script
- test_inference.py — Test script

## Quick Start
```bash
# Transfer this folder to Jetson
scp -r jetson_deploy/ jetson@<ip>:~/newgenes/

# On Jetson:
cd ~/newgenes
bash jetson_setup.sh
```

## Memory Budget (16GB shared)
- OS + CUDA runtime: ~2.5 GB
- Model weights (INT4 AWQ): ~10 GB (3-bit: ~8 GB)
- KV cache (seq_len=4096): ~1.5 GB
- Headroom: ~2 GB

## Alternative: llama.cpp (simpler)
If TensorRT-LLM setup is problematic:
```bash
# Convert to GGUF on any machine with enough RAM
python convert_hf_to_gguf.py base_model/ --outtype bf16 --outfile gemma4.gguf
llama-quantize gemma4.gguf gemma4-q4_k_m.gguf Q4_K_M

# On Jetson with llama.cpp (CUDA build):
./llama-server -m gemma4-q4_k_m.gguf --lora peft_adapter/ -ngl 99 -c 4096
```
"""
    with open(DEPLOY_DIR / "README.md", "w") as f:
        f.write(readme)

    # Summary
    total_size = sum(
        f.stat().st_size for f in DEPLOY_DIR.rglob("*") if f.is_file()
    )
    print(f"\n  Package created at {DEPLOY_DIR}/")
    print(f"  Total size: {total_size / 1e6:.1f} MB")
    print(f"\n  Contents:")
    for f in sorted(DEPLOY_DIR.rglob("*")):
        if f.is_file():
            rel = f.relative_to(DEPLOY_DIR)
            size = f.stat().st_size
            print(f"    {rel}  ({size / 1e6:.1f} MB)" if size > 1e6 else f"    {rel}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python deploy_jetson.py [prepare|package]")
        sys.exit(1)

    cmd = sys.argv[1].lower()
    if cmd == "prepare":
        prepare()
    elif cmd == "package":
        package()
    else:
        print(f"Unknown command: {cmd}")
